// generated by tools/gen.py from the web build. Do not edit by hand.
#pragma once
namespace vp {
enum Id {
  o1_on, o1_wave, o1_oct, o1_semi, o1_fine, o1_lvl, o1_uni, o1_det, o1_spr, o1_pw, o2_on, o2_wave, o2_oct, o2_semi, o2_fine, o2_lvl, o2_uni, o2_det, o2_spr, o2_pw, sub_lvl, sub_oct, sub_wave, noise_lvl, noise_tone, fm_amt, fm_ratio, fm_dec, pe_amt, pe_dec, f_type, f_cut, f_res, f_env, f_key, f_vel, fe_a, fe_d, fe_s, fe_r, ae_a, ae_d, ae_s, ae_r, ae_vel, l1_shape, l1_dest, l1_rate, l1_depth, l2_shape, l2_dest, l2_rate, l2_depth, v_mode, v_glide, v_voices, bpm, arp_on, arp_mode, arp_div, arp_oct, arp_gate, fx_drive, ch_rate, ch_depth, ch_mix, dl_div, dl_fb, dl_tone, dl_mix, rv_size, rv_damp, rv_mix, vol, trim, mw_dest, v_bend, NUM
};
enum Type { Num=0, Choice=1, Bool=2 };
struct Spec { const char* id; const char* name; int type; float min, max, def; bool expo; float step; int n; const char* const* names; const float* values; };
inline const char* const nm_o1_wave[] = {"SAW", "SQR", "TRI", "SIN", "PLS", "ORGN", "VOX", "HOLW", "GLAS", "REED"};
inline const float vl_o1_wave[] = {0.0f, 1.0f, 2.0f, 3.0f, 4.0f, 5.0f, 6.0f, 7.0f, 8.0f, 9.0f};
inline const char* const nm_o1_oct[] = {"-2", "-1", "0", "1", "2"};
inline const float vl_o1_oct[] = {-2.0f, -1.0f, 0.0f, 1.0f, 2.0f};
inline const char* const nm_o2_wave[] = {"SAW", "SQR", "TRI", "SIN", "PLS", "ORGN", "VOX", "HOLW", "GLAS", "REED"};
inline const float vl_o2_wave[] = {0.0f, 1.0f, 2.0f, 3.0f, 4.0f, 5.0f, 6.0f, 7.0f, 8.0f, 9.0f};
inline const char* const nm_o2_oct[] = {"-2", "-1", "0", "1", "2"};
inline const float vl_o2_oct[] = {-2.0f, -1.0f, 0.0f, 1.0f, 2.0f};
inline const char* const nm_sub_oct[] = {"-1", "-2"};
inline const float vl_sub_oct[] = {-1.0f, -2.0f};
inline const char* const nm_sub_wave[] = {"SIN", "SQR"};
inline const float vl_sub_wave[] = {0.0f, 1.0f};
inline const char* const nm_fm_ratio[] = {"x0.5", "x1", "x1.5", "x2", "x3", "x3.5", "x4", "x5", "x7"};
inline const float vl_fm_ratio[] = {0.5f, 1.0f, 1.5f, 2.0f, 3.0f, 3.5f, 4.0f, 5.0f, 7.0f};
inline const char* const nm_f_type[] = {"LP24", "LP12", "HP", "BP", "NTCH"};
inline const float vl_f_type[] = {0.0f, 1.0f, 2.0f, 3.0f, 4.0f};
inline const char* const nm_l1_shape[] = {"SIN", "TRI", "SAW", "SQR", "S&H"};
inline const float vl_l1_shape[] = {0.0f, 1.0f, 2.0f, 3.0f, 4.0f};
inline const char* const nm_l1_dest[] = {"PTCH", "CUT", "AMP", "PAN"};
inline const float vl_l1_dest[] = {0.0f, 1.0f, 2.0f, 3.0f};
inline const char* const nm_l2_shape[] = {"SIN", "TRI", "SAW", "SQR", "S&H"};
inline const float vl_l2_shape[] = {0.0f, 1.0f, 2.0f, 3.0f, 4.0f};
inline const char* const nm_l2_dest[] = {"PTCH", "CUT", "AMP", "PAN"};
inline const float vl_l2_dest[] = {0.0f, 1.0f, 2.0f, 3.0f};
inline const char* const nm_v_mode[] = {"POLY", "MONO", "LEGT"};
inline const float vl_v_mode[] = {0.0f, 1.0f, 2.0f};
inline const char* const nm_arp_mode[] = {"UP", "DOWN", "U/D", "RAND"};
inline const float vl_arp_mode[] = {0.0f, 1.0f, 2.0f, 3.0f};
inline const char* const nm_arp_div[] = {"1/4", "1/8", "1/8T", "1/16", "1/16T", "1/32"};
inline const float vl_arp_div[] = {1.0f, 0.5f, 0.3333333333333333f, 0.25f, 0.16666666666666666f, 0.125f};
inline const char* const nm_arp_oct[] = {"1", "2", "3"};
inline const float vl_arp_oct[] = {1.0f, 2.0f, 3.0f};
inline const char* const nm_dl_div[] = {"1/16", "1/8", "3/16", "1/4", "3/8", "1/2"};
inline const float vl_dl_div[] = {0.25f, 0.5f, 0.75f, 1.0f, 1.5f, 2.0f};
inline const char* const nm_mw_dest[] = {"VIB", "PTCH", "CUT", "LFO2"};
inline const float vl_mw_dest[] = {0.0f, 1.0f, 2.0f, 3.0f};
inline const char* const nm_v_bend[] = {"±2", "±7", "±12"};
inline const float vl_v_bend[] = {2.0f, 7.0f, 12.0f};
inline const Spec specs[NUM] = {
  {"o1_on", "Osc 1 On", Bool, 0.f, 1.f, 1.0f, false, 1.f, 2, nullptr, nullptr},
  {"o1_wave", "Osc 1 Wave", Choice, 0.f, 9.0f, 0.0f, false, 1.f, 10, nm_o1_wave, vl_o1_wave},
  {"o1_oct", "Osc 1 Oct", Choice, 0.f, 4.0f, 2.0f, false, 1.f, 5, nm_o1_oct, vl_o1_oct},
  {"o1_semi", "Osc 1 Semi", Num, -12.0f, 12.0f, 0.0f, false, 1.0f, 0, nullptr, nullptr},
  {"o1_fine", "Osc 1 Fine", Num, -50.0f, 50.0f, 0.0f, false, 1.0f, 0, nullptr, nullptr},
  {"o1_lvl", "Osc 1 Level", Num, 0.0f, 1.0f, 0.8f, false, 0.0f, 0, nullptr, nullptr},
  {"o1_uni", "Osc 1 Unison", Num, 1.0f, 7.0f, 1.0f, false, 1.0f, 0, nullptr, nullptr},
  {"o1_det", "Osc 1 Detune", Num, 0.0f, 50.0f, 12.0f, false, 1.0f, 0, nullptr, nullptr},
  {"o1_spr", "Osc 1 Spread", Num, 0.0f, 1.0f, 0.6f, false, 0.0f, 0, nullptr, nullptr},
  {"o1_pw", "Osc 1 Width", Num, 0.05f, 0.95f, 0.5f, false, 0.0f, 0, nullptr, nullptr},
  {"o2_on", "Osc 2 On", Bool, 0.f, 1.f, 0.0f, false, 1.f, 2, nullptr, nullptr},
  {"o2_wave", "Osc 2 Wave", Choice, 0.f, 9.0f, 0.0f, false, 1.f, 10, nm_o2_wave, vl_o2_wave},
  {"o2_oct", "Osc 2 Oct", Choice, 0.f, 4.0f, 2.0f, false, 1.f, 5, nm_o2_oct, vl_o2_oct},
  {"o2_semi", "Osc 2 Semi", Num, -12.0f, 12.0f, 0.0f, false, 1.0f, 0, nullptr, nullptr},
  {"o2_fine", "Osc 2 Fine", Num, -50.0f, 50.0f, 0.0f, false, 1.0f, 0, nullptr, nullptr},
  {"o2_lvl", "Osc 2 Level", Num, 0.0f, 1.0f, 0.6f, false, 0.0f, 0, nullptr, nullptr},
  {"o2_uni", "Osc 2 Unison", Num, 1.0f, 7.0f, 1.0f, false, 1.0f, 0, nullptr, nullptr},
  {"o2_det", "Osc 2 Detune", Num, 0.0f, 50.0f, 12.0f, false, 1.0f, 0, nullptr, nullptr},
  {"o2_spr", "Osc 2 Spread", Num, 0.0f, 1.0f, 0.6f, false, 0.0f, 0, nullptr, nullptr},
  {"o2_pw", "Osc 2 Width", Num, 0.05f, 0.95f, 0.5f, false, 0.0f, 0, nullptr, nullptr},
  {"sub_lvl", "Sub Level", Num, 0.0f, 1.0f, 0.0f, false, 0.0f, 0, nullptr, nullptr},
  {"sub_oct", "Sub Oct", Choice, 0.f, 1.0f, 0.0f, false, 1.f, 2, nm_sub_oct, vl_sub_oct},
  {"sub_wave", "Sub Wave", Choice, 0.f, 1.0f, 0.0f, false, 1.f, 2, nm_sub_wave, vl_sub_wave},
  {"noise_lvl", "Noise", Num, 0.0f, 1.0f, 0.0f, false, 0.0f, 0, nullptr, nullptr},
  {"noise_tone", "Noise Tone", Num, 200.0f, 16000.0f, 8000.0f, true, 0.0f, 0, nullptr, nullptr},
  {"fm_amt", "Fm Amount", Num, 0.0f, 1.0f, 0.0f, false, 0.0f, 0, nullptr, nullptr},
  {"fm_ratio", "Fm Ratio", Choice, 0.f, 8.0f, 3.0f, false, 1.f, 9, nm_fm_ratio, vl_fm_ratio},
  {"fm_dec", "Fm Decay", Num, 0.02f, 4.0f, 0.6f, true, 0.0f, 0, nullptr, nullptr},
  {"pe_amt", "Pitch Env", Num, -24.0f, 24.0f, 0.0f, false, 1.0f, 0, nullptr, nullptr},
  {"pe_dec", "Pitch Decay", Num, 0.005f, 2.0f, 0.08f, true, 0.0f, 0, nullptr, nullptr},
  {"f_type", "F Type", Choice, 0.f, 4.0f, 0.0f, false, 1.f, 5, nm_f_type, vl_f_type},
  {"f_cut", "Cutoff", Num, 30.0f, 18000.0f, 3000.0f, true, 0.0f, 0, nullptr, nullptr},
  {"f_res", "Resonance", Num, 0.0f, 1.0f, 0.15f, false, 0.0f, 0, nullptr, nullptr},
  {"f_env", "Filter Env", Num, -1.0f, 1.0f, 0.3f, false, 0.0f, 0, nullptr, nullptr},
  {"f_key", "Key Track", Num, 0.0f, 1.0f, 0.4f, false, 0.0f, 0, nullptr, nullptr},
  {"f_vel", "Velocity", Num, 0.0f, 1.0f, 0.3f, false, 0.0f, 0, nullptr, nullptr},
  {"fe_a", "Filter Env Attack", Num, 0.001f, 8.0f, 0.003f, true, 0.0f, 0, nullptr, nullptr},
  {"fe_d", "Filter Env Decay", Num, 0.005f, 8.0f, 0.35f, true, 0.0f, 0, nullptr, nullptr},
  {"fe_s", "Filter Env Sustain", Num, 0.0f, 1.0f, 0.3f, false, 0.0f, 0, nullptr, nullptr},
  {"fe_r", "Filter Env Release", Num, 0.005f, 8.0f, 0.4f, true, 0.0f, 0, nullptr, nullptr},
  {"ae_a", "Amp Env Attack", Num, 0.001f, 8.0f, 0.003f, true, 0.0f, 0, nullptr, nullptr},
  {"ae_d", "Amp Env Decay", Num, 0.005f, 8.0f, 0.3f, true, 0.0f, 0, nullptr, nullptr},
  {"ae_s", "Amp Env Sustain", Num, 0.0f, 1.0f, 0.8f, false, 0.0f, 0, nullptr, nullptr},
  {"ae_r", "Amp Env Release", Num, 0.005f, 8.0f, 0.3f, true, 0.0f, 0, nullptr, nullptr},
  {"ae_vel", "Amp Env Velocity", Num, 0.0f, 1.0f, 0.5f, false, 0.0f, 0, nullptr, nullptr},
  {"l1_shape", "Lfo 1 Shape", Choice, 0.f, 4.0f, 0.0f, false, 1.f, 5, nm_l1_shape, vl_l1_shape},
  {"l1_dest", "Lfo 1 Dest", Choice, 0.f, 3.0f, 0.0f, false, 1.f, 4, nm_l1_dest, vl_l1_dest},
  {"l1_rate", "Lfo 1 Rate", Num, 0.03f, 20.0f, 5.0f, true, 0.0f, 0, nullptr, nullptr},
  {"l1_depth", "Lfo 1 Depth", Num, 0.0f, 1.0f, 0.0f, false, 0.0f, 0, nullptr, nullptr},
  {"l2_shape", "Lfo 2 Shape", Choice, 0.f, 4.0f, 1.0f, false, 1.f, 5, nm_l2_shape, vl_l2_shape},
  {"l2_dest", "Lfo 2 Dest", Choice, 0.f, 3.0f, 1.0f, false, 1.f, 4, nm_l2_dest, vl_l2_dest},
  {"l2_rate", "Lfo 2 Rate", Num, 0.03f, 20.0f, 0.3f, true, 0.0f, 0, nullptr, nullptr},
  {"l2_depth", "Lfo 2 Depth", Num, 0.0f, 1.0f, 0.0f, false, 0.0f, 0, nullptr, nullptr},
  {"v_mode", "V Mode", Choice, 0.f, 2.0f, 0.0f, false, 1.f, 3, nm_v_mode, vl_v_mode},
  {"v_glide", "Glide", Num, 0.001f, 1.5f, 0.08f, true, 0.0f, 0, nullptr, nullptr},
  {"v_voices", "Voices", Num, 1.0f, 16.0f, 8.0f, false, 1.0f, 0, nullptr, nullptr},
  {"bpm", "Tempo", Num, 60.0f, 180.0f, 120.0f, false, 1.0f, 0, nullptr, nullptr},
  {"arp_on", "Arp On", Bool, 0.f, 1.f, 0.0f, false, 1.f, 2, nullptr, nullptr},
  {"arp_mode", "Arp Mode", Choice, 0.f, 3.0f, 0.0f, false, 1.f, 4, nm_arp_mode, vl_arp_mode},
  {"arp_div", "Arp Div", Choice, 0.f, 5.0f, 3.0f, false, 1.f, 6, nm_arp_div, vl_arp_div},
  {"arp_oct", "Arp Oct", Choice, 0.f, 2.0f, 0.0f, false, 1.f, 3, nm_arp_oct, vl_arp_oct},
  {"arp_gate", "Arp Gate", Num, 0.05f, 1.0f, 0.6f, false, 0.0f, 0, nullptr, nullptr},
  {"fx_drive", "Drive", Num, 0.0f, 1.0f, 0.0f, false, 0.0f, 0, nullptr, nullptr},
  {"ch_rate", "Chorus Rate", Num, 0.05f, 8.0f, 0.5f, true, 0.0f, 0, nullptr, nullptr},
  {"ch_depth", "Chorus Depth", Num, 0.0f, 1.0f, 0.4f, false, 0.0f, 0, nullptr, nullptr},
  {"ch_mix", "Chorus Mix", Num, 0.0f, 1.0f, 0.0f, false, 0.0f, 0, nullptr, nullptr},
  {"dl_div", "Dl Div", Choice, 0.f, 5.0f, 2.0f, false, 1.f, 6, nm_dl_div, vl_dl_div},
  {"dl_fb", "Feedback", Num, 0.0f, 0.9f, 0.35f, false, 0.0f, 0, nullptr, nullptr},
  {"dl_tone", "Delay Tone", Num, 400.0f, 16000.0f, 4500.0f, true, 0.0f, 0, nullptr, nullptr},
  {"dl_mix", "Delay Mix", Num, 0.0f, 1.0f, 0.0f, false, 0.0f, 0, nullptr, nullptr},
  {"rv_size", "Reverb Size", Num, 0.4f, 10.0f, 2.5f, true, 0.0f, 0, nullptr, nullptr},
  {"rv_damp", "Damping", Num, 0.0f, 1.0f, 0.5f, false, 0.0f, 0, nullptr, nullptr},
  {"rv_mix", "Reverb Mix", Num, 0.0f, 1.0f, 0.12f, false, 0.0f, 0, nullptr, nullptr},
  {"vol", "Volume", Num, 0.0f, 1.0f, 0.75f, false, 0.0f, 0, nullptr, nullptr},
  {"trim", "Trim", Num, 0.1f, 8.0f, 1.0f, false, 0.0f, 0, nullptr, nullptr},
  {"mw_dest", "Mod Wheel", Choice, 0.f, 3.0f, 0.0f, false, 1.f, 4, nm_mw_dest, vl_mw_dest},
  {"v_bend", "Bend Range", Choice, 0.f, 2.0f, 0.0f, false, 1.f, 3, nm_v_bend, vl_v_bend},
};
}
