# Generates Source/Params.h and Source/Presets.h from the web build's spec, so the
# plugin and the page can never drift apart. Re-run after changing index.html:
#   node tools/dump.js && python3 tools/gen.py
import json, os
here=os.path.dirname(os.path.abspath(__file__))
d=json.load(open(os.path.join(here,"vireo.json")))
spec,order,presets=d["spec"],d["order"],d["presets"]
DIVS={"1/4":1,"1/8":.5,"1/8T":1/3,"1/16":.25,"1/16T":1/6,"1/32":.125,"3/16":.75,"3/8":1.5,"1/2":2}
cid=lambda k:k.replace(".","_")
F=lambda v: repr(float(v))+"f"
def cstr(s): return '"'+s.replace('\\','\\\\').replace('"','\\"')+'"'
out=["// generated by tools/gen.py from the web build. Do not edit by hand.","#pragma once","namespace vp {","enum Id {"]
out.append("  "+", ".join(cid(k) for k in order)+", NUM")
out.append("};")
out.append("enum Type { Num=0, Choice=1, Bool=2 };")
out.append("struct Spec { const char* id; const char* name; int type; float min, max, def; bool expo; float step; int n; const char* const* names; const float* values; };")
for k in order:
    s=spec[k]
    if s["t"]=="o":
        names=s["names"]; opts=s["opts"]
        vals=[DIVS[o] if isinstance(o,str) and o in DIVS else (o if isinstance(o,(int,float)) else i) for i,o in enumerate(opts)]
        out.append(f"inline const char* const nm_{cid(k)}[] = {{{', '.join(cstr(str(n)) for n in names)}}};")
        out.append(f"inline const float vl_{cid(k)}[] = {{{', '.join(repr(float(v))+'f' for v in vals)}}};")
out.append("inline const Spec specs[NUM] = {")
for k in order:
    s=spec[k]; nm=s["label"].title()
    if s["t"]=="n": out.append(f"  {{{cstr(cid(k))}, {cstr(nm)}, Num, {F(s['min'])}, {F(s['max'])}, {F(s['def'])}, {'true' if s['curve']=='exp' else 'false'}, {F(s['step'] or 0)}, 0, nullptr, nullptr}},")
    elif s["t"]=="b": out.append(f"  {{{cstr(cid(k))}, {cstr(nm)}, Bool, 0.f, 1.f, {F(s['def'])}, false, 1.f, 2, nullptr, nullptr}},")
    else:
        di=s["opts"].index(s["def"])
        out.append(f"  {{{cstr(cid(k))}, {cstr(nm)}, Choice, 0.f, {F(len(s['opts'])-1)}, {F(di)}, false, 1.f, {len(s['opts'])}, nm_{cid(k)}, vl_{cid(k)}}},")
out.append("};")
out.append("}")
open(os.path.join(here,"..","Source","Params.h"),"w").write("\n".join(out)+"\n")
pr=["// generated by tools/gen.py from the web build. Do not edit by hand.","#pragma once","#include \"Params.h\"","namespace vp {",
    "struct Preset { const char* cat; const char* name; float v[NUM]; };",f"inline constexpr int NUM_PRESETS = {len(presets)};","inline const Preset presets[NUM_PRESETS] = {"]
for p in presets:
    vals=[]
    for k in order:
        s=spec[k]; v=p["p"][k]
        if s["t"]=="o": vals.append(float(s["opts"].index(v)))
        elif s["t"]=="b": vals.append(float(v))
        else: vals.append(float(v))
    pr.append(f"  {{{cstr(p['cat'])}, {cstr(p['name'])}, {{{', '.join(repr(round(v,6))+'f' for v in vals)}}}}},")
pr.append("};"); pr.append("}")
open(os.path.join(here,"..","Source","Presets.h"),"w").write("\n".join(pr)+"\n")
print("wrote",len(order),"params,",len(presets),"presets")
